version: '2'
services:
    invoice-postgresql:
        image: postgres:11.2
        volumes:
            - /data_db/postgres-001/:/var/lib/postgresql/data/:z
        environment:
            - POSTGRES_USER=invoice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
